export const Emoji = {
  Back: '🔙',
  Default: '✅',
  Additional: '◽️',
  Remove: '🗑️',
  Withdraw: '💸',
  Rename: '✏️',
  SetDefault: '🔄',
  Delete: '❌',
  Feature: '🔧',
  Wallet: '💼',
  Settings: '⚙️',
  AutoTrade: '🤖',
  ManualTrade: '👤',
  TradeSetting: '💰',
  Feed: '📰',
  Filters: '🔍',
  Help: '❓',
  Start: '🚀',
  Terms: '📜',
  Privacy: '🔒',
  Risk: '🚨',
  Service: '💻',
  User: '👤',
  Limitation: '🚫',
  Error: '❌',
  Success: '✅',
  Warning: '⚠️',
  Info: 'ℹ️',
  Question: '❓',
  Check: '✅',
  Cross: '❌',
  ArrowLeft: '⬅️',
};