name: Node.js CI/CD to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn

      - name: Run build
        run: yarn build:prod

      - name: Test SSH connection
        run: |
          echo "Testing SSH connection to ${{ secrets.EC2_HOST }}"
          timeout 10s ssh -o ConnectTimeout=5 -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "echo 'SSH connection successful'"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          timeout: 300s
          script: |
            cd /home/ec2-user/telegram-trading-bot
            git pull origin main
            
            yarn start:prod
